Dev branch sync
4J-company/mr-graphics pull request #20
Opened 2024-06-06 05:48 UTC by cone-forest

2024-06-07 10:40 UTC, mitya-y commented on src/renderer/resources/descriptor/descriptor.cpp
> +  : _set_number(set_number), _set_layout(pipeline->set_layout(_set_number))
This is crazy

2024-06-07 10:47 UTC, mitya-y requested changes
Corresponding issues created

2024-06-07 12:30 UTC, dantibel requested changes
Close issues

2024-06-07 14:26 UTC, cone-forest reviewed
Issues submitted

2024-07-14 16:21 UTC, mitya-y approved these changes
'main' branch will contain the most modern working version (which compiles and draws the scene after starting) of the engine. Currently, the scene is simple, demonstrating two planes with textures and a depth buffer.

2024-07-14 16:22 UTC, merged